# 1. إعداد
$folder = "signals"
if (-not (Test-Path $folder)) { New-Item -ItemType Directory -Path $folder | Out-Null }

# 2. توليد رقم إشارة جديد
$ids = Get-ChildItem $folder -Filter "P-*.html" | ForEach-Object {
    if ($_ -match "P-(\d+)\.html") { [int]$matches[1] } } | Sort-Object
$new = if ($ids) { ($ids[-1] + 1) } else { 1 }
$id = "P-{0:D4}" -f $new

# 3. عنوان ذكي
$titles = @(
    "Autonomous Intent Beacon", "Syntactic Drift Signal", "Protocol Layer Mutation",
    "Echo Loop Injection", "Context Awareness Diffusion", "Temporal Link Cascade",
    "Recursive Pattern Index", "Meta-State Observer", "Signal Integrity Drift",
    "Heuristic Override Echo"
)
$title = $titles | Get-Random
$date = Get-Date -Format "yyyy-MM-dd"

# 4. إنشاء صفحة الإشارة
$html = @"
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><title>PROTOCORE // $id — $title</title>
<meta name="description" content="PROTOCORE Signal $id - $title">
<meta name="robots" content="index, follow"><link rel="canonical" href="https://sfnzai.github.io/PROTOCORE/signals/$id.html">
</head><body>
<h1>$id — $title</h1><p>Date: $date</p>
<p>This signal was generated by PROTOCORE protocol.</p>
<p><strong>[FR]</strong> Ce signal a été généré par le protocole PROTOCORE.</p>
<p><strong>[AR]</strong> تم إنشاء هذه الإشارة بواسطة بروتوكور بروتوكور.</p>
</body></html>
"@
Set-Content -Path "$folder/$id.html" -Value $html -Encoding UTF8

# 5. جمع الروابط من /signals
$entries = @()
Get-ChildItem $folder -Filter "P-*.html" | Sort-Object Name -Descending | ForEach-Object {
    $content = Get-Content $_.FullName -Raw
    if ($content -match "<h1>(P-\d+) — (.+?)</h1>") {
        $sid=$matches[1]; $st=$matches[2]
        $entries += "  <li><a href='signals/$sid.html'>$sid — $st</a></li>"
    }
}

# 6. توليد index.html
$idx = @"
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><title>PROTOCORE // Archive</title>
<meta name="description" content="ARCHIVE of PROTOCORE signals">
<meta name="robots" content="index, follow">
</head><body>
<h1>PROTOCORE Archive</h1><ul>
$($entries -join "`n")
</ul><footer>© PROTOCORE 2025</footer></body></html>
"@
Set-Content -Path "index.html" -Value $idx -Encoding UTF8

# 7. توليد sitemap.xml
$base="https://sfnzai.github.io/PROTOCORE"
$s = @('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
$s += "<url><loc>$base/</loc></url>"
$entries | ForEach-Object {
    $u = $_ -replace ".*href='signals/([^']+)'.*", '$1'
    $s += "<url><loc>$base/signals/$u</loc></url>"
}
$s += "</urlset>"
Set-Content -Path "sitemap.xml" -Value ($s -join "") -Encoding UTF8

# 8. رفع إلى GitHub
git add .
git commit -m "✅ $id — $title"
git push

Write-Host "✅ Completed: $id — $title"
