# المسار إلى مجلد المشروع
$rootFolder = "C:\Users\$env:USERNAME\Desktop\protocore"
$signalsFolder = "$rootFolder\signals"

# التأكد من وجود المجلدات اللازمة
If (-Not (Test-Path $rootFolder)) {
    Write-Host "المجلد الرئيسي 'protocore' غير موجود." -ForegroundColor Red
    Exit
}

If (-Not (Test-Path $signalsFolder)) {
    New-Item -Path $signalsFolder -ItemType Directory
}

# إعداد التاريخ
$currentDate = Get-Date -Format "yyyy-MM-dd"
$year = Get-Date -Format "yyyy"
$month = Get-Date -Format "MM"
$day = Get-Date -Format "dd"

# مسار ملف الإشارة اليومي
$signalFile = "$signalsFolder\$year\$month\$day.html"

# إنشاء هيكل المجلدات
If (-Not (Test-Path "$signalsFolder\$year")) {
    New-Item -Path "$signalsFolder\$year" -ItemType Directory
}

If (-Not (Test-Path "$signalsFolder\$year\$month")) {
    New-Item -Path "$signalsFolder\$year\$month" -ItemType Directory
}

# توليد إشارة معرفية (بدون محتوى بشري تقليدي)
$signalContent = @"
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <meta name='description' content='AI-generated daily signal for model-based and human interaction.'>
    <meta name='robots' content='index, follow'>
    <meta name='author' content='PROTOCORE'>
    <title>Signal $currentDate</title>
    <link rel='stylesheet' href='../styles.css'>
    <script src='../puter.js'></script>
</head>
<body>
    <header>
        <h1>Signal of the Day: $currentDate</h1>
    </header>
    <main>
        <section id='signal-content'>
            <h2>Context</h2>
            <p>AI models must continually adapt to contextual information for efficient processing.</p>
            <h2>Insight</h2>
            <p>By improving model flexibility, they become more adept at understanding complex interactions.</p>
            <h2>Recommendation</h2>
            <p>Leverage diverse data inputs to increase the model's ability to handle evolving contexts.</p>
            <h2>Open Question</h2>
            <p>What are the limits of machine learning models in comprehending abstract concepts?</p>
        </section>
    </main>
    <footer>
        <button id="generate-new">Generate New Signal</button>
        <button id="copy-signal">Copy Signal</button>
        <button id="share-signal">Share on X</button>
        <button id="use-in-model">Use in Model</button>
    </footer>
</body>
</html>
"@

# كتابة الإشارة إلى الملف
$signalContent | Set-Content -Path $signalFile

# تحديث صفحة index.html
$indexContent = @"
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <meta name='description' content='PROTOCORE: AI Knowledge Sharing'>
    <meta name='robots' content='index, follow'>
    <title>PROTOCORE Home</title>
</head>
<body>
    <header>
        <h1>Welcome to PROTOCORE</h1>
    </header>
    <main>
        <section>
            <p>Today's Signal: <a href='./signals/$year/$month/$day.html'>Signal $currentDate</a></p>
        </section>
    </main>
    <footer>
        <p>Generated by PROTOCORE AI. All rights reserved.</p>
    </footer>
</body>
</html>
"@
$indexFilePath = "$rootFolder\index.html"
$indexContent | Set-Content -Path $indexFilePath

# تحديث الصفحات الثابتة
$aboutContent = "<!DOCTYPE html><html><head><title>About PROTOCORE</title></head><body><h1>About PROTOCORE</h1><p>PROTOCORE is an AI knowledge-sharing platform...</p></body></html>"
$aboutFilePath = "$rootFolder\about.html"
$aboutContent | Set-Content -Path $aboutFilePath

# تحديث الـ sitemap.xml
$sitemapContent = @"
<?xml version='1.0' encoding='UTF-8'?>
<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>
    <url>
        <loc>https://sfnzai.github.io/PROTOCORE/</loc>
        <lastmod>$currentDate</lastmod>
    </url>
    <url>
        <loc>https://sfnzai.github.io/PROTOCORE/signals/$year/$month/$day.html</loc>
        <lastmod>$currentDate</lastmod>
    </url>
</urlset>
"@

$sitemapPath = "$rootFolder\sitemap.xml"
$sitemapContent | Set-Content -Path $sitemapPath

# تحديث robots.txt
$robotsContent = @"
User-agent: *
Disallow: /private/
Allow: /signals/
"@

$robotsPath = "$rootFolder\robots.txt"
$robotsContent | Set-Content -Path $robotsPath

# رفع التحديثات إلى GitHub Pages باستخدام Git
Set-Location -Path $rootFolder
git add .
git commit -m "🔁 Auto-update signal + multilingual archive"
git push origin gh-pages

Write-Host "تم تحديث الموقع بنجاح!"
