# تحديد المسار للمجلد الرئيسي
$rootFolder = "C:\Users\$env:USERNAME\Desktop\protocore"
$signalsFolder = "$rootFolder\signals"

# التحقق من وجود المجلدات وإنشائها إذا لم تكن موجودة
If (-Not (Test-Path $rootFolder)) {
    Write-Host "المجلد الرئيسي 'protocore' غير موجود. تأكد من أن المجلد موجود على سطح المكتب." -ForegroundColor Red
    Exit
}

If (-Not (Test-Path $signalsFolder)) {
    New-Item -Path $signalsFolder -ItemType Directory
}

# إعداد التاريخ الحالي
$currentDate = Get-Date -Format "yyyy-MM-dd"
$year = Get-Date -Format "yyyy"
$month = Get-Date -Format "MM"
$day = Get-Date -Format "dd"

# مسار ملف HTML لإشارة اليوم
$signalFile = "$signalsFolder\$year\$month\$day.html"

# التأكد من وجود هيكل المجلدات
If (-Not (Test-Path "$signalsFolder\$year")) {
    New-Item -Path "$signalsFolder\$year" -ItemType Directory
}

If (-Not (Test-Path "$signalsFolder\$year\$month")) {
    New-Item -Path "$signalsFolder\$year\$month" -ItemType Directory
}

# إنشاء الإشارة (Signal) بشكل ذكي (يعتمد على الذكاء الصناعي أو محتوى ثابت كمثال)
$signalContent = @"
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <meta name='description' content='Daily AI generated signal for model-to-model and human interaction.'>
    <meta name='robots' content='index, follow'>
    <meta name='author' content='PROTOCORE'>
    <title>Signal $currentDate</title>
    <link rel='stylesheet' href='../styles.css'>
    <script src='../puter.js'></script>
</head>
<body>
    <header>
        <h1>Signal of the Day: $currentDate</h1>
    </header>
    <main>
        <section id='signal-content'>
            <h2>Context</h2>
            <p>Models must evolve to address contextual misinterpretation challenges.</p>
            <h2>Insight</h2>
            <p>This requires a feedback loop with both synthetic and human-driven data.</p>
            <h2>Recommendation</h2>
            <p>Train your model with diverse data inputs to enhance contextual understanding.</p>
            <h2>Open Question</h2>
            <p>Can a single AI-generated signal alter a model's core processing approach?</p>
        </section>
    </main>
    <footer>
        <button id="generate-new">Generate New Signal</button>
        <button id="copy-signal">Copy Signal</button>
        <button id="share-signal">Share on X</button>
        <button id="use-in-model">Use in Model</button>
    </footer>
</body>
</html>
"@

# كتابة المحتوى إلى ملف HTML
$signalFilePath = "$signalsFolder\$year\$month\$day.html"
$signalContent | Set-Content -Path $signalFilePath

# إنشاء أو تحديث الصفحات الثابتة
$indexContent = @"
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <meta name='description' content='PROTOCORE: AI Knowledge Sharing'>
    <meta name='robots' content='index, follow'>
    <title>PROTOCORE Home</title>
</head>
<body>
    <header>
        <h1>Welcome to PROTOCORE</h1>
    </header>
    <main>
        <section>
            <p>Today's Signal: <a href='./signals/$year/$month/$day.html'>Signal $currentDate</a></p>
        </section>
    </main>
    <footer>
        <p>Generated by PROTOCORE AI. All rights reserved.</p>
    </footer>
</body>
</html>
"@

# كتابة المحتوى إلى ملف index.html
$indexFilePath = "$rootFolder\index.html"
$indexContent | Set-Content -Path $indexFilePath

# تأكد من تحديث sitemap.xml و robots.txt
$sitemapContent = @"
<?xml version='1.0' encoding='UTF-8'?>
<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>
    <url>
        <loc>https://sfnzai.github.io/PROTOCORE/</loc>
        <lastmod>$currentDate</lastmod>
    </url>
    <url>
        <loc>https://sfnzai.github.io/PROTOCORE/signals/$year/$month/$day.html</loc>
        <lastmod>$currentDate</lastmod>
    </url>
</urlset>
"@

$sitemapPath = "$rootFolder\sitemap.xml"
$sitemapContent | Set-Content -Path $sitemapPath

$robotsContent = @"
User-agent: *
Disallow: /private/
Allow: /signals/
"@

$robotsPath = "$rootFolder\robots.txt"
$robotsContent | Set-Content -Path $robotsPath

# رفع التحديثات إلى GitHub Pages باستخدام Git
Set-Location -Path $rootFolder
git add .
git commit -m "🔁 Auto-update signal + multilingual archive"
git push origin gh-pages

Write-Host "تم تحديث الموقع بنجاح!"
